version: "3.9"


services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      API_TITLE: API doc dev
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge