spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: ${POSTGRES_URL:jdbc:mysql://localhost:3306/springboot}
        username: ${POSTGRES_USER:root}
        password: ${POSTGRES_PASSWORD:admin}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
            ddl-auto: none

openapi:
    service:
        api-docs: api-service
        server: http://localhost:${server.port}
        title: ${API_TITLE:DUMMY-API-TITLE}
        version: 1.0.0
        description: "API docs"
        serverUrl: "serverUrl"
        serverName: "serverName"